### PR TITLE
Mobile: add join meeting for voice channel event

### PR DESCRIPTION
**Pull request by hoangtranlehuy**
join meeting in voice channel event item and event detail.

### CODE REVIEW

**Comment by hoangtranlehuy** [comment]
https://github.com/user-attachments/assets/ac42c67e-89bb-4201-95a0-65c1b05f0d96

**Review by phuocnguyenncc — APPROVED** [review]

**Comment by hoangtranlehuy** [comment]
Screenshot_2024-10-04-15-29-28-671_com mobile mezon

**Comment by phuocnguyenncc** [comment]
chỗ này chưa căng giữa

image

**Comment by phuocnguyenncc** [comment]
check lại màu 

image

**Pull request merged**
